# Generated by Django 5.0.2 on 2024-03-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
