# Generated by Django 5.0.2 on 2024-04-29 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_friend_user_friendrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('game', models.CharField(max_length=100)),
                ('members_needed', models.IntegerField()),
                ('contact', models.CharField(max_length=100)),
            ],
        ),
    ]
