# Generated by Django 5.0.2 on 2024-04-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='creator',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
