# Generated by Django 5.0.2 on 2024-05-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='item_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
